version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates code coverage report
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage
      - cmd: cargo llvm-cov report --html
      - cmd: echo -e "\n\e[1;32mOpen coverage report\x3A\e[0m file:///$(pwd)/target/llvm-cov/html/index.html\n"

  covn:
    desc: Generates code coverage report using nextest
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov nextest --no-cfg-coverage
      - cmd: cargo llvm-cov report --html
      - cmd: echo -e "\n\e[1;32mOpen coverage report\x3A\e[0m file:///$(pwd)/target/llvm-cov/html/index.html\n"

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs tests in debug mode using nextest
    cmds:
      - cmd: cargo +stable nextest run

  help:
    desc: Runs htop help option
    cmds:
      - cmd: cargo +stable run -- -h

  help-long:
    desc: Runs htop help option
    cmds:
      - cmd: cargo +stable run -- --help

  install:
    desc: Builds and installs release version
    cmds:
      - cmd: cargo +stable install htop --path=. --force

  uninstall:
    desc: Uninstalls the release version
    cmds:
      - cmd: cargo +stable uninstall htop

  musl:
    desc: Builds using the Linux MUSL target
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-musl

  run:
    desc: Runs htop with provided arguments
    cmds:
      - cmd: cargo +stable run -- {{.CLI_ARGS}}
