#!/usr/bin/env bash

htop -v --margin=0 -p B0    single H_000010.html actual.1  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.1 | grep -E 'Page size:'
htop -v --margin=0 -p B1    single H_000010.html actual.2  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.2 | grep -E 'Page size:'
htop -v --margin=0 -p B2    single H_000010.html actual.3  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.3 | grep -E 'Page size:'
htop -v --margin=0 -p B3    single H_000010.html actual.4  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.4 | grep -E 'Page size:'
htop -v --margin=0 -p B4    single H_000010.html actual.5  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.5 | grep -E 'Page size:'
htop -v --margin=0 -p B5    single H_000010.html actual.6  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.6 | grep -E 'Page size:'
htop -v --margin=0 -p B6    single H_000010.html actual.7  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.7 | grep -E 'Page size:'
htop -v --margin=0 -p B7    single H_000010.html actual.8  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.8 | grep -E 'Page size:'
htop -v --margin=0 -p B8    single H_000010.html actual.9  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.9 | grep -E 'Page size:'
htop -v --margin=0 -p B9    single H_000010.html actual.10 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.10 | grep -E 'Page size:'
htop -v --margin=0 -p B10   single H_000010.html actual.11 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.11 | grep -E 'Page size:'
htop -v --margin=0 -p B11   single H_000010.html actual.12 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.12 | grep -E 'Page size:'
htop -v --margin=0 -p B12   single H_000010.html actual.13 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.13 | grep -E 'Page size:'
htop -v --margin=0 -p B13   single H_000010.html actual.14 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.14 | grep -E 'Page size:'
htop -v --margin=0 -p 'B0+' single H_000010.html actual.15 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.15 | grep -E 'Page size:'
htop -v --margin=0 -p 'B1+' single H_000010.html actual.16 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.16 | grep -E 'Page size:'
htop -v --margin=0 -p 'B2+' single H_000010.html actual.17 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.17 | grep -E 'Page size:'