#!/usr/bin/env bash

htop -v --margin=0 -p C0  single H_000010.html actual.1  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.1 | grep -E 'Page size:'
htop -v --margin=0 -p C1  single H_000010.html actual.2  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.2 | grep -E 'Page size:'
htop -v --margin=0 -p C2  single H_000010.html actual.3  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.3 | grep -E 'Page size:'
htop -v --margin=0 -p C3  single H_000010.html actual.4  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.4 | grep -E 'Page size:'
htop -v --margin=0 -p C4  single H_000010.html actual.5  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.5 | grep -E 'Page size:'
htop -v --margin=0 -p C5  single H_000010.html actual.6  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.6 | grep -E 'Page size:'
htop -v --margin=0 -p C6  single H_000010.html actual.7  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.7 | grep -E 'Page size:'
htop -v --margin=0 -p C7  single H_000010.html actual.8  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.8 | grep -E 'Page size:'
htop -v --margin=0 -p C8  single H_000010.html actual.9  2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.9 | grep -E 'Page size:'
htop -v --margin=0 -p C9  single H_000010.html actual.10 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.10 | grep -E 'Page size:'
htop -v --margin=0 -p C10 single H_000010.html actual.11 2>&1 | grep -E 'Page size:|Paper format:'
pdfinfo actual.11 | grep -E 'Page size:'