# Apple macOS ARM64

name: macOS ARM64

on:
  push:
    branches:
      - main
      - releases/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - run: cargo +stable build --release --target=aarch64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: htop-apple-macos-arm64
          path: target/aarch64-apple-darwin/release/htop
