# apple-macos-arm64

name: macOS ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - run: cargo build --release --target=aarch64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: htop-macos-arm64
          path: target/aarch64-apple-darwin/release/htop
